type Response {
    moods: [String]
    age: Int
    gender: String
    sexuality: String
    trans: Int
    country: String
    hue: Int
    hue_sentiment: Int
    saturation: Int
    saturation_sentiment: Int
    lightness: Int
    lightness_sentiment: Int
}

type Mood {
    name: String
    strength: Int
}

type Query {
  allResponses: [Response]
}